config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  post '/gossips/new', to: 'gossips#create'

  root 'home#index'

  resources :gossips

  devise_for :moussaillons
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :moussaillon
end

app/models/moussaillon.rb
class Moussaillon < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :gossips

  USERNAME_REGEX = /\A[a-zA-Z@]+\z/

 	#before_save { anonymous_username.downcase! }
	 
 	 validates :anonymous_username,
 	   presence: true,
 	   uniqueness: { case_sensitive: false },
 	   length: { minimum: 3, maximum: 42 },
 	   format: { with: USERNAME_REGEX, message: "Only allows letters" }

 	   attr_accessor :sign_up_code
  
  	   validates :sign_up_code,
       on: :create,
       presence: true,
       inclusion: { in: ["outwomaco"] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

   before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
  	devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:anonymous_username, :email, :password, :password_confirmation, :sign_up_code)}
  end
  
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
	def index
		@gossips = Gossip.all
	end

	def new
		@gossip = current_moussaillon.gossips.build
	end

	def create
		@gossip = current_moussaillon.gossips.build(gossip_params)
		if @gossip.save
  		   redirect_to @gossip
  		else
    	   render 'new'
  		end
	end

	def show
		@gossip = Gossip.find(params[:id])
	end

	def edit
		 @gossip = Gossip.find(params[:id])
	end

	def update
		@gossip = Gossip.find(params[:id])
 
  		if @gossip.update(gossip_params)
    	   redirect_to @gossip
  		else
    	   render 'edit'
  		end
	end

	def destroy
		@gossip = Gossip.find(params[:id])
  		@gossip.destroy
 
  		redirect_to gossips_path
	end

	private
   		 # Use callbacks to share common setup or constraints between actions.
    	 def set_gossip
     	 	@gossip = Gossip.find(params[:id])
    	 end

   		# Never trust parameters from the scary internet, only allow the white list through.
    	def gossip_params
      	params.require(:gossip).permit(:title, :content, :anonymous_username, :user_id)
   		end

   	end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@gossips = Gossip.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/gossips/edit.html.erb
<h1>Edit gossip</h1>
 
 <%= form_with(model: @gossip) do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
  <%end%>
 
<%= link_to 'Back', gossips_path %>

app/views/gossips/index.html.erb
<div class=row>
 <div class=center-block style=float:none;>
   <h4>Ne rien manquer des coulisses de The Hacking Project</h4></br></br></br></br></br>
 </div>
</div>

  <div class="container">
    <div class=center-block style=float:none;>
  <table class="table table-hover">
    <thead>
        <tr>
          <th>Titre</th>
          <th>Contenu</th>
          <th>Délateur</th>
          <th>Show</th>
          <th>Edit</th>
          <th>Destroy</th>
        </tr>
      </thead>
      <tbody>
        <% @gossips.each do |gossip| %>
        <tr>
        <td><%= gossip.title %></td>
        <td><%= gossip.content %></td>
        <td><%= gossip.moussaillon.anonymous_username %></td>
        <td><%= link_to 'Show', gossip_path(gossip) %></td>
          <td><%= link_to 'Edit', edit_gossip_path(gossip) %></td>
            <td><%= link_to 'Destroy', gossip_path(gossip),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
      </tr>
    </tbody>
    <%end%>
  </table>
  </div>
  </div>

 <ul class="nav justify-content-center">
    <li class="nav-item">
      <a class="nav-link" href="#">
      <%= link_to "Edit Account", edit_moussaillon_registration_path %></a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="#">
    <%= link_to "Sign Out", destroy_moussaillon_session_path, method: :delete %></a>
    </li>
  </ul>

app/views/gossips/new.html.erb
<div class=row>
 
 <div class=col-md-2 col-md-offset-5></div>

<%= form_with scope: :gossip, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

</div>

</div>

app/views/gossips/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @gossip.title %>
</p>
 
<p>
  <strong>Content:</strong>
  <%= @gossip.content %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @gossip.moussaillon.anonymous_username %>
</p>

<p>
  <%= @gossip.created_at %></br>
  <%= @gossip.updated_at %>
</p>

<%= link_to 'Edit', edit_gossip_path(@gossip) %>
<%= link_to 'Back', gossips_path %>

app/views/home/index.html.erb
<h4>Ne rien manquer des coulisses de The Hacking Project</h4></br></br></br></br></br>

<ul class="nav justify-content-center">
<% if moussaillon_signed_in? %>
	<div class="container">
	<table class="table table-hover">
		<thead>
  			<tr>
   	 			<th>Titre</th>
    			<th>Contenu</th>
    			<th>Délateur</th>
    			<th>Show</th>
    			<th>Edit</th>
    			<th>Destroy</th>
  			</tr>
  		</thead>
  		<tbody>
				<% @gossips.each do |gossip| %>
				<tr>
				<td><%= gossip.title %></td>
				<td><%= gossip.content %></td>
				<td><%= gossip.moussaillon.anonymous_username %></td>
				<td><%= link_to 'Show', gossip_path(gossip) %></td>
     			<td><%= link_to 'Edit', edit_gossip_path(gossip) %></td>
      			<td><%= link_to 'Destroy', gossip_path(gossip),
              		method: :delete,
              		data: { confirm: 'Are you sure?' } %></td>
			</tr>
		</tbody>
		<%end%>
	</table>

	</div>

		<li class="nav-item">
			<a class="nav-link" href="#">
			<%= link_to "Edit Account", edit_moussaillon_registration_path %></a>
		</li>

		<li class="nav-item">
			<a class="nav-link" href="#">
		<%= link_to "Sign Out", destroy_moussaillon_session_path, method: :delete %></a>
		</li>

<% else %>
<li>
<%= link_to "Sign In", new_moussaillon_session_path %>
</li>
<li>
<%= link_to "Sign Up", new_moussaillon_registration_path %>
</li>
</ul>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'GOSSIP PROJECT', root_path, class: 'navbar-brand' %>
        </div>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Home', root_path, class: 'nav-link' %></li>
            <% if !moussaillon_signed_in? %>
              <li><%= link_to 'Sign In', new_moussaillon_session_path, class: 'nav-link' %></li>
              <li><%= link_to 'Sign Up', new_moussaillon_registration_path, class: 'nav-link' %></li>
            <% else %>
              <li><%= link_to 'New Gossip',new_gossip_path, class: 'nav-link' %></li>
              <li><%= link_to 'Sign Out', destroy_moussaillon_session_path, class: 'nav-link',
                  method: :delete %></li>
              <li>
              	<a href="#" class="nav-link">
              		<%= current_moussaillon.anonymous_username %>
              	</a>	
              </li>
              <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>